version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: ./pipeline.wdl
    name: salmon-rnaseq-wdl
  - subclass: CWL
    primaryDescriptorPath: ./pipeline.cwl
    name: salmon-rnaseq-cwl
