version: "3.9"
services:
    analysis:
      image: hubmap/scrna-analysis
      build: 
        context: ./
        dockerfile: docker/analysis/Dockerfile
      # restart: always
    barcode_adj:
      image: hubmap/scrna-barcode-adj
      build: 
        context: ./
        dockerfile: docker/barcode_adj/Dockerfile
      # restart: always
    trim_reads:
      image: hubmap/scrna-trim-reads
      build: 
        context: ./
        dockerfile: docker/trim_reads/Dockerfile
      # restart: always
    salmon:
      image: hubmap/salmon-grch38
      build: 
        context: ./
        dockerfile: docker/salmon/Dockerfile
      # restart: always