name: squidpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.10
  - pip
  - squidpy==1.2.3
  - pip:
      - anndata==0.12.7
      - numpy==1.22.0
      - pandas==1.3.0
      - manhole~=1.8
      - opencv-python
