name: deepscence
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pip
  - anndata==0.9.2
  - pip:
      - git+https://github.com/hubmapconsortium/DeepScence.git
      - tensorflow==2.12.*
      - git+https://github.com/anthony-qu/dca_patched.git